### ISSUE TITLE
How to build Obfuscator-LLVM

### ISSUE THREAD

**Issue by man3kin3ko** [icyguider/Nimcrypt2#15]
While trying to build obfuscator using [project instrustions](https://github.com/heroims/obfuscator/wiki/Installation) I got an undocumented error:
```
[ 58%] Linking CXX static library ../../../../lib/libclangAnalysis.a
[ 58%] Built target clangAnalysis
make: *** [Makefile:156: all] Error 2
```
Issues in the original repo are closed without any answers. Maybe anybody here know how to deal with it? 
OS: `Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux`, launched in VirtualBox

Compiler: `gcc (Debian 12.2.0-3) 12.2.0`

I will provide more info if you ask me to.

**Comment by icyguider** [comment]
Hi @kperevoznikova,

My only piece of advice would be to perhaps allocate more CPU cores or RAM to the VM you are performing the compilation in. I have noticed that more resources tend to make a difference. As I said in the readme, you should be able to do it with a little perseverance as others were able to. I am closing this issue since it doesn't relate to a problem with this project and therefore cannot be fixed.

**Comment by man3kin3ko** [comment]
Sure, thank you
