### ISSUE TITLE
Cannot run output file from a x64bit PE.

### ISSUE THREAD

**Issue by spookycheekybreeky** [icyguider/Nimcrypt2#17]
Hi, i try to use your tools with a compiled c program that print hello world into a cmd. But i cant get it running with your RunPE.

The command that i use to create my final exe
```
nim r nimcrypt.nim --no-ppid-spoof -s -n -g -v -u -t pe -f test_app.exe
```
and the output i get when lunching the "a.exe" is the following:

```
C:\Users\zingstrok\Desktop\Nimcrypt2-main>a.exe
[*] Found Syscall Stub: NtOpenProcess
[*] Found Syscall Stub: NtAllocateVirtualMemory
[*] Found Syscall Stub: NtWriteVirtualMemory
[*] Found Syscall Stub: NtCreateThreadEx
[*] Found Syscall Stub: NtProtectVirtualMemory
[*] Found Syscall Stub: NtClose
[*] Found Syscall Stub: NtQueueApcThread
[*] Found Syscall Stub: NtAlertResumeThread
[*] Found Syscall Stub: NtWaitForSingleObject
[*] Unhook ntdll: true
[*] Applying amsi patch: true
[*] Applying etw patch: true
[*] Decrypting packed exe...
[+] Exe File Prefer Image Base at

Size:
16384
[+] Mapping Section ...
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

here the code for the small test_app.exe
```
#include <stdio.h>

int main() {
    printf("This is a testing app, this app should run in 64bit...");

    return 0;
}
```

do you know why i get this error ?

Thank

**Comment by icyguider** [comment]
I compiled your example with Mingw, used Nimcrypt with the same arguments, and had no issues executing the resulting exe on Windows 10 & 11 virtual machines. I also had no problems when I compiled the example with wclang or MSVC.

<details>
  <summary>See Screenshot</summary>

<img width="1663" alt="Mingw Compiled PE Example" src="https://user-images.githubusercontent.com/79864975/215330087-34f5de0d-8cde-4297-85e8-db01c2dd4ad6.png">
</details>

The error you posted is an unspecific error that others have seen in various odd cases. I'm sure you could figure out whatever's going on here, but you'll have to do some basic debugging. I will close this thread however since I am unable to replicate your issue. Feel free to reopen it if you ever figure out what the actual issue was.
