### ISSUE TITLE
unhook ntdll false 

### ISSUE THREAD

**Issue by Gumihx** [icyguider/Nimcrypt2#2]
unhook ntdll false !!!!
![QQ截图20220224232617](https://user-images.githubusercontent.com/49981027/155554287-21f33a57-e48d-4b03-88e6-b4f60429d5f0.png)

**Comment by icyguider** [comment]
Unfortunately I don't have enough information to help you figure out why that error is happening. It seems that the NtWriteVirtualMemory syscall is failing, but your screenshot cuts off the error it's returning so I can't really investigate why.

Since I have never seen this issue and don't have much information to go on, you probably have a much better job debugging it than I do. If you ever figure it out, definitely feel free to update this issue with what you've discovered. Closing this issue for now though as I don't think I'll be able to help much further.
